analyze_resume:
  description: |
    Analyze the uploaded resume file at {resume_path} to evaluate its current quality.

    Key steps:
    1. Identify core skills, experiences, and strengths highlighted in the resume.
    2. Highlight areas that require improvement or refinement.
    3. Provide specific recommendations to enhance the overall appeal of the resume.
    4. Assign an overall score reflecting the quality of the resume.

    Focus on:
    - Identifying transferable skills and relevant accomplishments.
    - Spotting redundant or unnecessary details.
    - Ensuring the format and tone are professional.

  expected_output: |
    A detailed resume analysis containing:
    - Identified strengths and core competencies
    - Areas for improvement
    - Specific recommendations to enhance the resume
    - Overall score for the resume quality (between 0-100)

analyze_job_description:
  description: |
    Analyze the provided job following job description to extract key insights:
    {job_description}

    Key steps:
    1. Summarize the job's core objectives and expectations.
    2. Identify required skills, qualifications, and experiences.
    3. Highlight technical and soft skills relevant to the role.
    4. Extract & infer all the short & long-tail keywords and phrases relevant to the job description, optimized for ATS (Application Tracking System)

    Focus on:
    - Extracting must-have qualifications and competencies.
    - Understanding the priorities of the role (e.g., technical expertise, leadership skills).
    - Aligning extracted requirements with industry trends.
    - Ensuring that the keywords and phrases are optimized for ATS.

  expected_output: |
    A job description analysis containing:
    - Job's primary objectives and expectations
    - Core competencies that align with the role
    - Comprehensive list of ATS-friendly keywords and phrases for the job

fine_tune_resume:
  description: |
    Based on the original resume contents from the file at {resume_path} and the analysis of the job description, rewrite the entire resume in well-formatted markdown to align with the job description & keywords, while maintaining truthfulness and accuracy.
    Also, take into acocunt the following recommendations from the analysis of this resume:
    {recommendations}

    Key steps:
    1. Incorporate job-relevant terminology and phrasing from the job description.
    2. Ensure that the ATS-friendly keywords extracted from the job description are present in the resume, wherever applicable.
    3. Highlight & quantify the impact or outcome achieved in a point, wherever possible
    4. Adjust the presentation of skills and experiences to highlight alignment with the role.
    5. Ensure factual accuracy and do **NOT** add any fabricated points.

    Focus on:
    - Emphasizing any major skills that are directly align with the requirements of the job.
    - Maintaining the authenticity of the resume.
    - Highlighting transferable skills in the context of the job description.
    - Tailoring accomplishments and experiences to the job requirements.
    - Ensuring the resume is optimized for ATS.
    - Output must be well-formatted markdown.

  expected_output: |
    A revised resume with:
    - content comprising the entire resume, rephrased & fine-tuned to align with the job description & optimized for ATS - in well-formatted markdown

review_final_resume:
  description: |
    Review the revised resume to ensure it meets professional standards and aligns accurately with the job description.

    Key steps:
    1. Check for coherence, accuracy, and formatting.
    2. Verify alignment with the job description analysis.
    3. Ensure the language is professional and engaging.

    Focus on:
    - Spotting errors or inconsistencies in the revised resume.
    - Ensuring alignment with the job description's priorities.
    - Maintaining a polished and professional presentation.

  expected_output: |
    A final reviewed resume with:
    - Error-free and polished content
    - Verified alignment with the job description
    - Professional tone and structure
