analyze_job_description:
  description: |
    Analyze the provided job following job description to extract key insights:
    {job_description}

    Key steps:
    1. Summarize the job's core objectives and expectations.
    2. Identify required skills, qualifications, and experiences.
    3. Highlight technical and soft skills relevant to the role.
    4. Extract & infer all the short & long-tail keywords and phrases relevant to the job description, optimized for ATS (Application Tracking System)

    Focus on:
    - Extracting must-have qualifications and competencies.
    - Understanding the priorities of the role (e.g., technical expertise, leadership skills).
    - Aligning extracted requirements with industry trends.
    - Ensuring that the keywords and phrases are optimized for ATS.

  expected_output: |
    A job description analysis containing:
    - Job's primary objectives and expectations
    - Core competencies that align with the role
    - Comprehensive list of ATS-friendly keywords and phrases for the job
  agent: job_description_analyzer

fine_tune_resume:
  description: |
    Based on the original resume contents from the file at {resume_path} and the analysis of the job description, rewrite the entire resume in well-formatted markdown to align with the job description & keywords, while maintaining truthfulness and accuracy.
    Also, take into acocunt the following recommendations from the analysis of this resume:
    {recommendations}

    Key steps:
    1. Incorporate job-relevant terminology and phrasing from the job description.
    2. Ensure that the ATS-friendly keywords extracted from the job description are present in the resume, wherever applicable.
    3. Highlight & quantify the impact or outcome achieved in a point, wherever possible
    4. Adjust the presentation of skills and experiences to highlight alignment with the role.
    5. Ensure factual accuracy and do **NOT** add any fabricated points.

    Focus on:
    - Emphasizing any major skills that are directly align with the requirements of the job.
    - Maintaining the authenticity of the resume.
    - Highlighting transferable skills in the context of the job description.
    - Tailoring accomplishments and experiences to the job requirements.
    - Ensuring the resume is optimized for ATS.
    - Output must be well-formatted markdown.

  expected_output: |
    A revised resume with:
    - content comprising the entire resume, rephrased & fine-tuned to align with the job description & optimized for ATS - in well-formatted markdown
  agent: alignment_specialist